//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dvd()
        {
            this.dvd_partaker = new HashSet<dvd_partaker>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string upc { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<int> studio_id { get; set; }
        public Nullable<int> aspect_code { get; set; }
        public Nullable<int> rating_code { get; set; }
        public Nullable<int> genre_code { get; set; }
        public Nullable<int> status_code { get; set; }
    
        public virtual aspect aspect { get; set; }
        public virtual genre genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dvd_partaker> dvd_partaker { get; set; }
        public virtual rating rating { get; set; }
        public virtual status status { get; set; }
        public virtual studio studio { get; set; }
    }
}
